name: example
description: An example project for the flutter spinkit.

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
