name: flutter_spinkit
description: A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
version: 0.0.1
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/flutter_spinkit

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
